from area import *
from candidato import *
from comuna import *
from comuna_view import *
from contactos_loader import *
from csv_reader import *
from dato import *
from estrellitas import *
from home import *
from indice import *
from messages import *
from molesta_a_un_candidato import *
from respuesta import *
from sin_datos import *
from templates import *
from templatetags import *
from ranking import *